# Dependencies
markdown:      kramdown
highlighter:   rouge
permalink:     none
sass:
    sass_dir:   _sass

exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile','bundle/','docker-compose.yml','micheltol.gemspec','README.md','LICENSE.txt']
include: ["_pages"]

applicationsettings:
    title: MichelTol.nl
    description: Michel Tol is een developer, vader, mud- & obstaclerunner. Michel betreedt de wereld met een pragmatisch can do/just do-it mentaliteit.
    keywords: Obstacle running, mudrun, Spartan, Strong Viking, Blog, Developer, wordtraveler
    author: Michel Tol
    hotjar: true
    wordCountPerMinute: 130
    thankyouurl: http://www.micheltol.nl/thank-you/
    disqus:
    shortname:        'micheltol'      
    google_analytics:   'UA-4573188-6'
    