version: '3'
services:
  web:
    image: jekyll/builder:latest
    command: jekyll serve --watch --force_polling --trace --incremental
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
    volumes:
      - .:/srv/jekyll
      - ./bundle:/usr/local/bundle