version: '3'
services:
  web:
    image: starefossen/github-pages
    command: jekyll serve --watch --force_polling
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
    volumes:
      - .:/srv/jekyll